# Generated by Django 3.2.9 on 2023-08-03 07:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('photos', djongo.models.fields.JSONField()),
                ('classifications', djongo.models.fields.JSONField()),
                ('detections', djongo.models.fields.JSONField()),
                ('caption', models.TextField(max_length=500)),
                ('ammenities', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
