# Generated by Django 4.2.3 on 2023-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
