# Generated by Django 4.2.3 on 2023-07-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_mainpage_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpage",
            name="text",
        ),
    ]
