# Generated by Django 4.2.3 on 2023-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_remove_mainpage_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
